[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --no-audit --prefer-offline"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start" 