[variables]
CI = "false"
GENERATE_SOURCEMAP = "false"
NPM_CONFIG_PRODUCTION = "false"

[providers.node]
version = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm ci --legacy-peer-deps"
]

[phases.build]
cmds = [
    "npm run build:prod"
]

[start]
cmd = "npx serve -s build -p $PORT"