[build]
builder = "nixpacks"

[variables]
CI = "false"
PORT = "3000"

[deploy]
startCommand = "npm run build && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 